chore(ci): pin coverage
Just released v7 breaks the build:

  No data to report.
  Error: ERROR: InvocationError for command /home/runner/work/django-allauth/django-allauth/.tox/py37-django30/bin/coverage report (exited with code 1)